### ISSUE TITLE
Proper Placement in UI of accepted Price after receiving an Order

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/business-process-service#23]
Receiving an order, the indication of the accepted price in a separate tab is confusing.

**Comment by suatgonul** [comment]
The overall idea in presentation of the business process steps is as follows:

1. Present the details of the product associated to the business process in "Product Characteristics" and "Product Trading & DElivery Terms".

**Comment by suatgonul** [comment]
This issue is obsolete as of the new UI.
