### ISSUE TITLE
Context sensitive User Interface

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/business-process-service#31]
E.g.: A transport service “product” has a link to search for transport service in the order response page.

**Comment by jinnerbichler** [comment]
We need to make a list of UI components, which are affected.

**Comment by suatgonul** [comment]
Regarding the first comment: To prevent a misunderstanding: The button is already there. Wernher had indicated that this is a possible scenario where the intermediary transport service providers might be looking for companies who provides the actual service. 

Regarding the general context-aware user interfaces, we should identify what should we implement exactly. Potential examples:
- Context-aware informative messages for users to guide them about the usage of the UI elements they face with. 
- Filtering the product / service search results automatically to include only the transportation services if the user is looking for a transportation service. 

Let's aim these for the release 3.

**Comment by suatgonul** [comment]
Navigating via the "search for transport service provider" button, results are filtered automatically to keep only the logistics services.
