### ISSUE TITLE
Improve Communication in Information Request Business Process [19Jan2018-1215]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/business-process-service#8]
The communication during the “information request” does not allow the requester to answer to the product provider’s response. I need to create another information request to respond.

**Comment by jinnerbichler** [comment]
At the time being, it is "hidden" under the tab "Quotation Details" (see screenshot). Therefore, it is not immediately visible/understandable how to proceed.

![image](https://user-images.githubusercontent.com/2677628/36026490-9ecb30ae-0d97-11e8-8a25-06c808c84bf0.png)

**Comment by jinnerbichler** [comment]
Additionally, it might not be clear that information (e.g. product configuration) is transferred to the following up Order Process.

**Comment by suatgonul** [comment]
I suggest to involve @oliver-jung for bringing his UX expertise to re-design the follow up procedures between business process. 

Actually, the logic described by @jinnerbichler is valid for all related business processes. For example, seller parties are able to initiate a Dispatch Advice from an Order Response; buyer parties initiate an Order from Quotation; or another Request for Quotation from Quotation.

**Comment by suatgonul** [comment]
Fixed with the new UI.
